spring.datasource.url=jdbc:postgresql://dpg-d68uen3h46gs73fl1p70-a.frankfurt-postgres.render.com:5432/reddit_clone_hugbunadarverk_un46
spring.datasource.username=reddit_clone_hugbunadarverk_un46_user
spring.datasource.password=vDE732eqwl2NrbXzO8zUGt4A1EaWlYOV
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080
