spring.datasource.url=jdbc:postgresql://dpg-d7gcc4a8qa3s73dniclg-a.frankfurt-postgres.render.com:5432/hugbunadarverkefni2final?sslmode=require
spring.datasource.username=hugbunadarverkefni2final_user
spring.datasource.password=zdYcIQ1CvzOCcTRIA3WPenHjnYz5gXMg
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.h2.console.enabled=false

server.port=8080
